package com.company.project.model;

import java.math.BigDecimal;
import java.util.Date;

public class TAccount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACCOUNT.ID
     *
     * @mbg.generated Sun Feb 07 17:46:36 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACCOUNT.GLOBAL_ID
     *
     * @mbg.generated Sun Feb 07 17:46:36 CST 2021
     */
    private String globalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACCOUNT.TOTAL_AMT
     *
     * @mbg.generated Sun Feb 07 17:46:36 CST 2021
     */
    private BigDecimal totalAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACCOUNT.FROZEN_AMT
     *
     * @mbg.generated Sun Feb 07 17:46:36 CST 2021
     */
    private BigDecimal frozenAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACCOUNT.HOT_ACCOUNT
     *
     * @mbg.generated Sun Feb 07 17:46:36 CST 2021
     */
    private Byte hotAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACCOUNT.CR_DATETIME
     *
     * @mbg.generated Sun Feb 07 17:46:36 CST 2021
     */
    private Date crDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACCOUNT.LM_DATETIME
     *
     * @mbg.generated Sun Feb 07 17:46:36 CST 2021
     */
    private Date lmDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACCOUNT.VERSION
     *
     * @mbg.generated Sun Feb 07 17:46:36 CST 2021
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACCOUNT.ID
     *
     * @return the value of T_ACCOUNT.ID
     *
     * @mbg.generated Sun Feb 07 17:46:36 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACCOUNT.ID
     *
     * @param id the value for T_ACCOUNT.ID
     *
     * @mbg.generated Sun Feb 07 17:46:36 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACCOUNT.GLOBAL_ID
     *
     * @return the value of T_ACCOUNT.GLOBAL_ID
     *
     * @mbg.generated Sun Feb 07 17:46:36 CST 2021
     */
    public String getGlobalId() {
        return globalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACCOUNT.GLOBAL_ID
     *
     * @param globalId the value for T_ACCOUNT.GLOBAL_ID
     *
     * @mbg.generated Sun Feb 07 17:46:36 CST 2021
     */
    public void setGlobalId(String globalId) {
        this.globalId = globalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACCOUNT.TOTAL_AMT
     *
     * @return the value of T_ACCOUNT.TOTAL_AMT
     *
     * @mbg.generated Sun Feb 07 17:46:36 CST 2021
     */
    public BigDecimal getTotalAmt() {
        return totalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACCOUNT.TOTAL_AMT
     *
     * @param totalAmt the value for T_ACCOUNT.TOTAL_AMT
     *
     * @mbg.generated Sun Feb 07 17:46:36 CST 2021
     */
    public void setTotalAmt(BigDecimal totalAmt) {
        this.totalAmt = totalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACCOUNT.FROZEN_AMT
     *
     * @return the value of T_ACCOUNT.FROZEN_AMT
     *
     * @mbg.generated Sun Feb 07 17:46:36 CST 2021
     */
    public BigDecimal getFrozenAmt() {
        return frozenAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACCOUNT.FROZEN_AMT
     *
     * @param frozenAmt the value for T_ACCOUNT.FROZEN_AMT
     *
     * @mbg.generated Sun Feb 07 17:46:36 CST 2021
     */
    public void setFrozenAmt(BigDecimal frozenAmt) {
        this.frozenAmt = frozenAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACCOUNT.HOT_ACCOUNT
     *
     * @return the value of T_ACCOUNT.HOT_ACCOUNT
     *
     * @mbg.generated Sun Feb 07 17:46:36 CST 2021
     */
    public Byte getHotAccount() {
        return hotAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACCOUNT.HOT_ACCOUNT
     *
     * @param hotAccount the value for T_ACCOUNT.HOT_ACCOUNT
     *
     * @mbg.generated Sun Feb 07 17:46:36 CST 2021
     */
    public void setHotAccount(Byte hotAccount) {
        this.hotAccount = hotAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACCOUNT.CR_DATETIME
     *
     * @return the value of T_ACCOUNT.CR_DATETIME
     *
     * @mbg.generated Sun Feb 07 17:46:36 CST 2021
     */
    public Date getCrDatetime() {
        return crDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACCOUNT.CR_DATETIME
     *
     * @param crDatetime the value for T_ACCOUNT.CR_DATETIME
     *
     * @mbg.generated Sun Feb 07 17:46:36 CST 2021
     */
    public void setCrDatetime(Date crDatetime) {
        this.crDatetime = crDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACCOUNT.LM_DATETIME
     *
     * @return the value of T_ACCOUNT.LM_DATETIME
     *
     * @mbg.generated Sun Feb 07 17:46:36 CST 2021
     */
    public Date getLmDatetime() {
        return lmDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACCOUNT.LM_DATETIME
     *
     * @param lmDatetime the value for T_ACCOUNT.LM_DATETIME
     *
     * @mbg.generated Sun Feb 07 17:46:36 CST 2021
     */
    public void setLmDatetime(Date lmDatetime) {
        this.lmDatetime = lmDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACCOUNT.VERSION
     *
     * @return the value of T_ACCOUNT.VERSION
     *
     * @mbg.generated Sun Feb 07 17:46:36 CST 2021
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACCOUNT.VERSION
     *
     * @param version the value for T_ACCOUNT.VERSION
     *
     * @mbg.generated Sun Feb 07 17:46:36 CST 2021
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACCOUNT
     *
     * @mbg.generated Sun Feb 07 17:46:36 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", globalId=").append(globalId);
        sb.append(", totalAmt=").append(totalAmt);
        sb.append(", frozenAmt=").append(frozenAmt);
        sb.append(", hotAccount=").append(hotAccount);
        sb.append(", crDatetime=").append(crDatetime);
        sb.append(", lmDatetime=").append(lmDatetime);
        sb.append(", version=").append(version);
        sb.append("]");
        return sb.toString();
    }
}