package com.company.project.mapper;

import com.company.project.model.TAccount;
import com.company.project.model.TAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACCOUNT
     *
     * @mbg.generated Fri Feb 05 17:33:26 CST 2021
     */
    long countByExample(TAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACCOUNT
     *
     * @mbg.generated Fri Feb 05 17:33:26 CST 2021
     */
    int deleteByExample(TAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACCOUNT
     *
     * @mbg.generated Fri Feb 05 17:33:26 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACCOUNT
     *
     * @mbg.generated Fri Feb 05 17:33:26 CST 2021
     */
    int insert(TAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACCOUNT
     *
     * @mbg.generated Fri Feb 05 17:33:26 CST 2021
     */
    int insertSelective(TAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACCOUNT
     *
     * @mbg.generated Fri Feb 05 17:33:26 CST 2021
     */
    List<TAccount> selectByExample(TAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACCOUNT
     *
     * @mbg.generated Fri Feb 05 17:33:26 CST 2021
     */
    TAccount selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACCOUNT
     *
     * @mbg.generated Fri Feb 05 17:33:26 CST 2021
     */
    int updateByExampleSelective(@Param("record") TAccount record, @Param("example") TAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACCOUNT
     *
     * @mbg.generated Fri Feb 05 17:33:26 CST 2021
     */
    int updateByExample(@Param("record") TAccount record, @Param("example") TAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACCOUNT
     *
     * @mbg.generated Fri Feb 05 17:33:26 CST 2021
     */
    int updateByPrimaryKeySelective(TAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACCOUNT
     *
     * @mbg.generated Fri Feb 05 17:33:26 CST 2021
     */
    int updateByPrimaryKey(TAccount record);
}